### ISSUE TITLE
Test is broken, please fix this ASAP

### ISSUE THREAD

**Issue by VeraKulemina** [learn-co-curriculum/phase-3-ruby-oo-inheritance-inheritance-lab#6]
### Canvas Link

https://learning.flatironschool.com/courses/5236/assignments/210677?confetti=true&submitted=0

### Concern

Test even with solution doesnt want to pass

**Comment by jlboba** [comment]
Hello, and thank you for raising this concern. Apologies for the delay in responding. 

However, I'm having difficulty reproducing the issue, all tests passed for me when I 
ran them on the `solution` branch. 

As such, I'll be closing this issue for now. If you can provide further detail or any 
additional relevant information about your development environment, feel free to 
reopen the issue with them and I'd be happy to take a second look!
