### ISSUE TITLE
Inconsistency between readme and the testing flow of lab

### ISSUE THREAD

**Issue by dovid11564** [learn-co-curriculum/phase-3-ruby-oo-inheritance-inheritance-lab#7]
### Canvas Link

https://learning.flatironschool.com/courses/5243/assignments/216854?module_item_id=504888

### Concern

The readme dictates that after setting your attr_accessor in lib/user.rb, the user should move to the teacher.rb file. This contradicts the tests, which after running through the user file check the student.rb file. 

### Suggested Changes

Change the readme or the tests so that they are consistent with each other.

**Comment by jlboba** [comment]
Hello, and thank you for providing feedback.

We have updated the GitHub repo and believe your issue to have been resolved.
Note, however, that if you are working in Canvas the changes may not show up
there, but they will for future students.

We appreciate your support! 💙
